development:
  adapter: postgresql
  encoding: unicode
  database: store_development
  pool: 5
  host: localhost
  username: blog
  password: 123


test:
  adapter: postgresql
  encoding: unicode
  database: store_test
  pool: 5
  host: localhost
  username: blog
  password: 123


production:
  adapter: postgresql
  encoding: unicode
  database: store_production
  pool: 5
  host: localhost
  username: blog
  password: 123

